language: ruby

rvm:
  - 2.2.2

services:
  - mysql
  - redis-server

before_script:
  - sudo sed -i 's/\(\* InnoDB\)/\1\ninnodb_file_format = Barracuda\ninnodb_large_prefix = 1\ninnodb_file_per_table_true/' /etc/mysql/my.cnf
  - cat /etc/mysql/my.cnf
  - sudo service mysql restart
  - cp config/database.travis.yml config/database.yml

script:
  - export RACK_ENV=test
  - rake db:setup
  - rake test
